FROM ubuntu:24.04

LABEL maintainer="Lam Hung"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    sudo \
    openjdk-8-jdk \
    ssh \
    openssh-server \
    openssh-client \
    && apt clean

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV HADOOP_VERSION=3.4.2
ENV HADOOP_HOME=/opt/hadoop-$HADOOP_VERSION
ENV HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
ENV PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin

ENV HDFS_NAMENODE_USER=root
ENV HDFS_DATANODE_USER=root
ENV HDFS_SECONDARYNAMENODE_USER=root
ENV YARN_RESOURCEMANAGER_USER=root
ENV YARN_NODEMANAGER_USER=root

RUN ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa && \
    cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && \
    chmod 0600 ~/.ssh/authorized_keys && \
    echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config

COPY ./hadoop-3.4.2.tar.gz /opt
RUN tar -xzf /opt/hadoop-3.4.2.tar.gz -C /opt
RUN rm /opt/hadoop-${HADOOP_VERSION}.tar.gz

# RUN wget https://dlcdn.apache.org/hadoop/common/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz -P /opt && \
#     tar -xzf /opt/hadoop-$HADOOP_VERSION.tar.gz && \
#     rm /opt/hadoop-$HADOOP_VERSION.tar.gz

RUN echo "export JAVA_HOME=$JAVA_HOME" >> $HADOOP_CONF_DIR/hadoop-env.sh

RUN sed -i '/<configuration>/a\
    <property>\n\
        <name>fs.defaultFS</name>\n\
        <value>hdfs://localhost:9000</value>\n\
    </property>' $HADOOP_CONF_DIR/core-site.xml

RUN sed -i '/<configuration>/a\
    <property>\n\
        <name>dfs.replication</name>\n\
        <value>1</value>\n\
    </property>' $HADOOP_CONF_DIR/hdfs-site.xml

RUN sed -i '/<configuration>/a\
    <property>\n\
        <name>mapreduce.framework.name</name>\n\
        <value>yarn</value>\n\
    </property>\n\
    <property>\n\
        <name>mapreduce.application.classpath</name>\n\
        <value>$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/*:$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/lib/*</value>\n\
    </property>' $HADOOP_CONF_DIR/mapred-site.xml

RUN sed -i '/<configuration>/a\
    <property>\n\
        <name>yarn.nodemanager.aux-services</name>\n\
        <value>mapreduce_shuffle</value>\n\
    </property>\n\
    <property>\n\
        <name>yarn.nodemanager.env-whitelist</name>\n\
        <value>JAVA_HOME,HADOOP_COMMON_HOME,HADOOP_HDFS_HOME,HADOOP_CONF_DIR,CLASSPATH_PREPEND_DISTCACHE,HADOOP_YARN_HOME,HADOOP_MAPRED_HOME</value>\n\
    </property>' $HADOOP_CONF_DIR/yarn-site.xml

COPY ./bootstrap.sh ${HADOOP_HOME}/bootstrap.sh
RUN chmod +x ${HADOOP_HOME}/bootstrap.sh

# 9870: NameNode UI, 8088: ResourceManager UI, 9000: HDFS URI
EXPOSE 9870 8088 9000 9864

CMD ["/bin/bash", "-c", "${HADOOP_HOME}/bootstrap.sh"]